version: '3.8'

services:
  mariadbProductos:
    container_name: "mariadbProductos"
    image: mariadb:latest
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: "mariadb1234"
      MYSQL_DATABASE: "productos"
      MYSQL_USER: "mariadb"
      MYSQL_PASSWORD: "mariadb1234"
    volumes:
      - db:/var/lib/mariadb/data

  supertechnology-productos:
    build: .
    container_name: "supertechnology-productos"
    environment:
      - MARIADB_CONNECTION:r2dbc:mariadb://mariadb:mariadb1234@mariadbProductos/productos
    ports:
      - '6963:6963'
    depends_on:
      - mariadbProductos

volumes:
  db:
    driver: local