version: '3.8'

services:
  postgresUsers:
    container_name: "postgresUsers"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres1234
      - POSTGRES_DB=usuarios
    volumes:
      - db:/var/lib/postgresql/data

  supertechnology-usuarios:
    build: .
    container_name: "supertechnology-usuarios"
    environment:
      - POSTGRES_CONNECTION=r2dbc:postgresql://postgres:postgres1234@postgresUsers/usuarios
      - JWT_SECRET=Zanahoria_Turbopropulsada9
      - KEY_STORE_PATH=classpath:cert/server_key.p12
    ports:
      - '6969:6969'
    depends_on:
      - postgresUsers

volumes:
  db:
    driver: local
